# Generated by Django 5.2.3 on 2025-07-02 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerTrustedNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_level', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('removed', 'Removed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('invitation_id', models.UUIDField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_networks', to=settings.AUTH_USER_MODEL)),
                ('trusted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_trusted_networks',
                'indexes': [models.Index(fields=['owner', 'status'], name='owner_trust_owner_i_d3d87e_idx'), models.Index(fields=['trusted_user', 'status'], name='owner_trust_trusted_e41db4_idx'), models.Index(fields=['trust_level'], name='owner_trust_trust_l_e11efc_idx')],
                'unique_together': {('owner', 'trusted_user')},
            },
        ),
        migrations.CreateModel(
            name='TrustedNetworkInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invitee_name', models.CharField(blank=True, max_length=255)),
                ('trust_level', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('personal_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_network_invitations',
                'indexes': [models.Index(fields=['invitation_token'], name='trusted_net_invitat_2094e9_idx'), models.Index(fields=['owner', 'status'], name='trusted_net_owner_i_43248e_idx'), models.Index(fields=['email', 'status'], name='trusted_net_email_0733eb_idx'), models.Index(fields=['expires_at'], name='trusted_net_expires_8673c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustLevelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_level_definitions',
                'indexes': [models.Index(fields=['owner', 'level'], name='trust_level_owner_i_b99ce5_idx')],
                'unique_together': {('owner', 'level')},
            },
        ),
    ]
