# Generated by Django 5.2.3 on 2025-07-03 17:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trustednetworkinvitation',
            name='trusted_net_invitat_2094e9_idx',
        ),
        migrations.AlterField(
            model_name='ownertrustednetwork',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('removed', 'Removed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownertrustednetwork',
            name='trust_level',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trustednetworkinvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='trustednetworkinvitation',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trustednetworkinvitation',
            name='invitation_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='trustednetworkinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trustleveldefinition',
            name='level',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='ownertrustednetwork',
            index=models.Index(fields=['added_at'], name='owner_trust_added_a_4ac4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trustednetworkinvitation',
            index=models.Index(fields=['created_at'], name='trusted_net_created_7515d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='trustednetworkinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('owner', 'email'), name='unique_pending_network_invitation'),
        ),
    ]
