# Generated by Django 5.2.3 on 2025-07-02 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('metric_data', models.JSONField(blank=True, default=dict)),
                ('date_recorded', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_analytics',
                'indexes': [models.Index(fields=['metric_name', 'date_recorded'], name='admin_analy_metric__97b0ee_idx'), models.Index(fields=['date_recorded'], name='admin_analy_date_re_473044_idx')],
                'unique_together': {('metric_name', 'date_recorded')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'), models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx'), models.Index(fields=['resource_type', 'resource_id'], name='activity_lo_resourc_31a457_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx')],
            },
        ),
    ]
