# Generated by Django 5.2.3 on 2025-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_role'], name='users_current_62fd23_idx'),
        ),
    ]
