# Generated by Django 5.2.3 on 2025-07-02 01:20

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('max_guests', models.PositiveIntegerField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved_pending_beds24', 'Approved Pending Beds24'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('beds24_property_id', models.CharField(blank=True, max_length=100)),
                ('beds24_sync_status', models.CharField(blank=True, max_length=50)),
                ('beds24_sync_data', models.JSONField(blank=True, default=dict)),
                ('beds24_synced_at', models.DateTimeField(blank=True, null=True)),
                ('beds24_error_message', models.TextField(blank=True)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('ical_import_url', models.URLField(blank=True, help_text='URL to import external bookings')),
                ('ical_export_url', models.URLField(blank=True, help_text='URL for other platforms to import our bookings')),
                ('ical_sync_enabled', models.BooleanField(default=True)),
                ('ical_last_sync', models.DateTimeField(blank=True, null=True)),
                ('ical_sync_status', models.CharField(blank=True, max_length=50)),
                ('ical_external_calendars', models.JSONField(blank=True, default=list)),
                ('ical_sync_interval', models.PositiveIntegerField(default=3600)),
                ('ical_auto_block', models.BooleanField(default=True)),
                ('ical_timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyICalSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('external_calendar_url', models.URLField(blank=True)),
                ('external_calendar_name', models.CharField(blank=True, max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bookings_imported', models.PositiveIntegerField(default=0)),
                ('bookings_exported', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_syncs', to='properties.property')),
            ],
            options={
                'db_table': 'property_ical_syncs',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties_owner_i_56c14d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'status'], name='properties_city_6c1708_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['beds24_property_id'], name='properties_beds24__e2c880_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties_created_abda95_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyicalsync',
            index=models.Index(fields=['property', 'sync_status'], name='property_ic_propert_1eef6a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyicalsync',
            index=models.Index(fields=['started_at'], name='property_ic_started_52166a_idx'),
        ),
    ]
