# Generated by Django 5.2.3 on 2025-07-10 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_remove_propertyicalsync_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_properties',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='saved_prope_user_id_a37cb8_idx'), models.Index(fields=['property'], name='saved_prope_propert_91936d_idx'), models.Index(fields=['saved_at'], name='saved_prope_saved_a_cd17cd_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
