# Generated by Django 5.2.3 on 2025-07-15 05:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_savedproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_availability',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='accessibility_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='bed_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_lead_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant Book'), ('request', 'Request to Book')], default='request', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_window',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='property',
            name='business_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict'), ('super_strict_30', 'Super Strict 30'), ('super_strict_60', 'Super Strict 60')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time_start',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AddField(
            model_name='property',
            name='children_welcome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='events_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='extra_guest_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='property',
            name='extra_guest_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='guest_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='instant_book_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='last_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='local_laws_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_stay',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='multi_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='place_type',
            field=models.CharField(choices=[('entire_place', 'Entire place'), ('private_room', 'Private room'), ('shared_room', 'Shared room')], db_index=True, default='entire_place', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='professional_hosting_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='professional_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('cabin', 'Cabin'), ('villa', 'Villa'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('loft', 'Loft'), ('castle', 'Castle'), ('treehouse', 'Treehouse'), ('boat', 'Boat'), ('camper', 'Camper/RV'), ('tent', 'Tent'), ('other', 'Other')], db_index=True, default='apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='safety_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='self_check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='transit_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='room_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'place_type'], name='properties_propert_fc4c18_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['max_guests', 'bedrooms'], name='properties_max_gue_2b14a2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['booking_type', 'instant_book_enabled'], name='properties_booking_6cfa1d_idx'),
        ),
        migrations.AddField(
            model_name='propertyavailability',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_set', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['property', 'date', 'status'], name='property_av_propert_91073c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['date', 'status'], name='property_av_date_c0ef91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyavailability',
            unique_together={('property', 'date')},
        ),
    ]
