# Generated by Django 5.2.3 on 2025-07-03 17:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitation',
            name='invitations_invitat_9c6805_idx',
        ),
        migrations.AddField(
            model_name='invitation',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingtoken',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='onboardingtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='onboardingtoken',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invitation_type', 'status'], name='invitations_invitat_4d021b_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['created_at'], name='invitations_created_acaa38_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email', 'invitation_type'), name='unique_pending_invitation_per_email_type'),
        ),
    ]
